BOARD = uno
F_CPU = 1000000UL # this is important for the sampling rate
MONITOR = /dev/ttyUSB0
AVRDUDE_ARD_BAUDRATE = 9600 # con 1MHz non puoi avere 152000 di baud

include /usr/share/arduino/Arduino.mk
